out: main.o dicionario.o linkedlist.o 
	gcc main.o dicionario.o linkedlist.o -lm

main.o: main.c
	gcc -c main.c

dicionario.o: dicionario.c
	gcc -c dicionario.c

linkedlist.o: linkedlist.c
	gcc -c linkedlist.c